services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exapp-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - API_INTERNAL_URL=${API_INTERNAL_URL:-http://backend:8000} #バックエンドコンテナに向ける
    networks:
      - exapp-network
    restart: unless-stopped

networks:
  exapp-network:
    external: true
    name: exapp-backend_exapp-network #バックエンドのコンテナを起動しておくこと